<?php

namespace DeployHuman\fortnox\Enum;

enum HouseWorkType: string
{
    case CONSTRUCTION = 'CONSTRUCTION';

    case ELECTRICITY = 'ELECTRICITY';

    case GLASSMETALWORK = 'GLASSMETALWORK';

    case GROUNDDRAINAGEWORK = 'GROUNDDRAINAGEWORK';

    case MASONRY = 'MASONRY';

    case PAINTINGWALLPAPERING = 'PAINTINGWALLPAPERING';

    case HVAC = 'HVAC';

    case MAJORAPPLIANCEREPAIR = 'MAJORAPPLIANCEREPAIR';

    case MOVINGSERVICES = 'MOVINGSERVICES';

    case ITSERVICES = 'ITSERVICES';

    case CLEANING = 'CLEANING';

    case TEXTILECLOTHING = 'TEXTILECLOTHING';

    case SNOWPLOWING = 'SNOWPLOWING';

    case GARDENING = 'GARDENING';

    case BABYSITTING = 'BABYSITTING';

    case OTHERCARE = 'OTHERCARE';

    case OTHERCOSTS = 'OTHERCOSTS';

    case SOLARCELLS = 'SOLARCELLS';

    case STORAGESELFPRODUCEDELECTRICITY = 'STORAGESELFPRODUCEDELECTRICITY';

    case CHARGINGSTATIONELECTRICVEHICLE = 'CHARGINGSTATIONELECTRICVEHICLE';

    case HOMEMAINTENANCE = 'HOMEMAINTENANCE';

    case FURNISHING = 'FURNISHING';

    case TRANSPORTATIONSERVICES = 'TRANSPORTATIONSERVICES';

    case WASHINGANDCAREOFCLOTHING = 'WASHINGANDCAREOFCLOTHING';
}
